# Generated by Django 4.2.4 on 2023-08-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_remove_producto_precio_proveedor_factura_pendiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=85, max_digits=10),
            preserve_default=False,
        ),
    ]
